
quic_frame_types = {
    0x00: 'PADDING',
    0x01: 'PING',
    0x02: 'ACK',
    0x03: 'ACK',
    0x04: 'RESET_STREAM',
    0x05: 'STOP_SENDING',
    0x06: 'CRYPTO',
    0x07: 'NEW_TOKEN',
    0x08: 'STREAM',
    0x09: 'STREAM',
    0x0a: 'STREAM',
    0x0b: 'STREAM',
    0x0c: 'STREAM',
    0x0d: 'STREAM',
    0x0e: 'STREAM',
    0x0f: 'STREAM',
    0x10: 'MAX_DATA',
    0x11: 'MAX_STREAM_DATA',
    0x12: 'MAX_STREAMS',
    0x13: 'MAX_STREAMS',
    0x14: 'DATA_BLOCKED',
    0x15: 'STREAM_DATA_BLOCKED',
    0x16: 'STREAMS_BLOCKED',
    0x17: 'STREAMS_BLOCKED',
    0x18: 'NEW_CONNECTION_ID',
    0x19: 'RETIRE_CONNECTION_ID',
    0x1a: 'PATH_CHALLENGE',
    0x1b: 'PATH_RESPONSE',
    0x1c: 'CONNECTION_CLOSE',
    0x1d: 'CONNECTION_CLOSE',
    0x1e: 'HANDSHAKE_DONE'
    }

# https://www.iana.org/assignments/quic/quic.xhtml#quic-transport
#   awk -F',' '{printf("    %s: \"%s\",\n", $1, $2);}' quic-transport.csv
quic_transport_param_types = {
    0x00: "original_destination_connection_id",
    0x01: "max_idle_timeout",
    0x02: "stateless_reset_token",
    0x03: "max_udp_payload_size",
    0x04: "initial_max_data",
    0x05: "initial_max_stream_data_bidi_local",
    0x06: "initial_max_stream_data_bidi_remote",
    0x07: "initial_max_stream_data_uni",
    0x08: "initial_max_streams_bidi",
    0x09: "initial_max_streams_uni",
    0x0a: "ack_delay_exponent",
    0x0b: "max_ack_delay",
    0x0c: "disable_active_migration",
    0x0d: "preferred_address",
    0x0e: "active_connection_id_limit",
    0x0f: "initial_source_connection_id",
    0x10: "retry_source_connection_id",
    0x11: "version_information",
    0x20: "max_datagram_frame_size",
    0x173e: "discard",
    0x26ab: "google handshake message",
    0x2ab2: "grease_quic_bit",
    0x3127: "initial_rtt",
    0x3128: "google_connection_options",
    0x3129: "user_agent",
    0x4752: "google_version",
}
