[package]
name = "conversion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.1"
rust-crypto = "0.2.36"
byteorder = "1.4.3"